config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  private     :string
#

class Goal < ApplicationRecord
  validates :title, :description, :private, :user, presence: true

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum:6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :goals, dependent: :destroy

  attr_reader :password

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    @user && @user.is_password?(password) ? @user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url unless current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_user
  before_action :verify_user, only: [:edit, :update, :delete]

  def new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def delete
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(@goal.user)
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :description, :private)
  end

  def verify_user
    @goal = Goal.find(params[:id])
    redirect_to user_url(current_user) unless @goal.user_id == current_user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: :show

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/delete.html.erb
<h1>Goals#delete</h1>
<p>Find me in app/views/goals/delete.html.erb</p>

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

app/views/goals/new.html.erb
<h1>Goals#new</h1>

<form action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="goal[title]">
  </label>

  <label>Description
    <textarea name="goal[description]"></textarea>
  </label>

  <select id="private_options" name="goal[private]">
    <option selected value="private">private</option>
    <option value="public">public</option>
  </select>

  <input type="submit" name="" value="Add Goal">
</form>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <%= error %>
        <% end %>
      </ul>
    <% end %>

    <% if current_user %>
      <%= current_user.username %>
      <%= button_to("Sign Out", "/session", method: :delete) %>
    <% else %>
      <%= link_to("Sign Up", "/users/new") %>
      <%= link_to("Sign In", "/session/new") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="" action="/users" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label> Username
  <input type="text" name="user[username]" value="">
  </label>

  <label> Password
  <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up!">

</form>

app/views/users/show.html.erb
<h1>Show Page</h1>

<%= @user.username %>

<hr>

<p>Goals:</p>
<%= link_to("Add Goal", new_goal_url) %>
<ul>
  <% @user.goals.each do |goal| %>
    <% if @user == current_user %>
      <li><%= goal.title %>
      <%= button_to("Edit Goal", edit_goal_url, method: :get) %></li>
    <% else %>
      <li><%= goal.title if goal.private == "public" %>
      <%= button_to("Edit Goal", edit_goal_url, method: :get) %></li>
    <% end %>
  <% end %>
</ul>